# Generated by Django 2.0.2 on 2020-04-24 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0003_resultlink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResultLink',
        ),
        migrations.AlterField(
            model_name='posts',
            name='desc',
            field=models.TextField(),
        ),
    ]
