# Generated by Django 2.0.2 on 2020-04-25 13:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0004_auto_20200425_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='desc',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
